2025-02-05 16:14:00,975 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for money.test
2025-02-05 16:14:00,979 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for money.test
2025-02-05 16:14:00,989 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for money.test
2025-02-05 16:14:00,996 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for money.test
2025-02-05 16:14:01,005 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_calendar.google_calendar.sync because it was found in queue for money.test
2025-02-05 16:14:01,008 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for money.test
2025-02-05 16:14:01,012 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for money.test
2025-02-05 16:14:01,014 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for money.test
2025-02-05 16:14:01,018 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for money.test
2025-02-05 16:30:00,370 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for money.test
2025-02-05 16:30:00,372 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for money.test
2025-02-05 16:30:00,381 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for money.test
2025-02-05 16:51:18,678 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for money.test
2025-02-05 16:51:18,685 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for money.test
2025-02-05 16:51:18,688 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for money.test
2025-02-05 16:51:18,694 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for money.test
2025-02-05 16:51:18,706 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for money.test
2025-02-05 16:51:18,711 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for money.test
2025-02-05 16:51:18,724 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for money.test
2025-02-05 16:51:18,727 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for money.test
2025-02-05 16:51:18,729 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for money.test
2025-02-05 16:51:18,734 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for money.test
2025-02-05 16:51:18,773 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for mysite.test
2025-02-05 16:51:18,777 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for mysite.test
2025-02-05 16:51:18,783 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for mysite.test
2025-02-05 16:58:00,987 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for money.test
2025-02-05 17:22:00,525 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for money.test
2025-02-05 17:22:00,532 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for money.test
2025-02-05 17:22:00,538 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for money.test
2025-02-05 17:22:00,543 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for money.test
2025-02-05 17:22:00,550 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for money.test
2025-02-05 17:22:00,557 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for money.test
2025-02-05 17:22:00,563 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for money.test
2025-02-05 17:22:00,565 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for money.test
2025-02-05 17:22:00,567 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for money.test
2025-02-05 17:22:00,580 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for mysite.test
2025-02-05 17:22:00,593 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for mysite.test
2025-02-05 17:22:00,598 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for mysite.test
2025-02-05 17:22:00,608 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for mysite.test
2025-02-05 17:22:00,614 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for mysite.test
2025-02-05 17:22:00,618 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for mysite.test
2025-02-05 17:22:00,620 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for mysite.test
2025-02-05 17:22:00,621 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for mysite.test
2025-02-05 17:26:00,658 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for mysite.test
2025-02-05 17:26:00,671 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for mysite.test
2025-02-05 17:26:00,678 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for mysite.test
2025-02-05 17:26:00,683 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for mysite.test
2025-02-05 17:26:00,690 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for mysite.test
2025-02-05 17:26:00,704 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for mysite.test
2025-02-05 17:26:00,711 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for money.test
2025-02-05 17:26:00,714 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for money.test
2025-02-05 17:26:00,719 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for money.test
2025-02-05 17:26:00,722 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for money.test
2025-02-05 17:26:00,731 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for money.test
2025-02-05 17:26:00,743 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for money.test
2025-02-05 17:26:00,746 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for money.test
2025-02-05 17:26:00,755 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for money.test
2025-02-05 17:26:00,758 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for money.test
2025-02-05 17:30:00,802 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for money.test
2025-02-05 17:30:00,807 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for money.test
2025-02-05 17:30:00,817 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for money.test
2025-02-05 17:30:00,826 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for money.test
2025-02-05 17:30:00,830 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for money.test
2025-02-05 17:30:00,832 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for money.test
2025-02-05 17:30:00,834 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for money.test
2025-02-05 17:30:00,840 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for money.test
2025-02-05 17:30:00,842 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for money.test
2025-02-05 17:30:00,847 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for money.test
2025-02-05 17:30:00,849 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for money.test
2025-02-05 17:30:00,853 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for mysite.test
2025-02-05 17:30:00,859 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for mysite.test
2025-02-05 17:30:00,865 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for mysite.test
2025-02-05 17:30:00,869 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for mysite.test
2025-02-05 17:30:00,883 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for mysite.test
2025-02-05 17:30:00,888 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for mysite.test
2025-02-05 17:34:00,912 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for mysite.test
2025-02-05 17:34:00,927 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for mysite.test
2025-02-05 17:34:00,932 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for mysite.test
2025-02-05 17:34:00,940 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for mysite.test
2025-02-05 17:34:00,953 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for mysite.test
2025-02-05 17:34:00,956 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for mysite.test
2025-02-05 17:34:00,958 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for mysite.test
2025-02-05 17:34:00,963 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for mysite.test
2025-02-05 17:34:00,985 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for money.test
2025-02-05 17:34:00,989 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for money.test
2025-02-05 18:06:00,721 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for mysite.test
2025-02-05 18:06:00,728 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for mysite.test
2025-02-05 18:06:00,735 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for mysite.test
2025-02-05 18:06:00,748 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for mysite.test
2025-02-05 18:06:00,750 ERROR scheduler Skipped queueing frappe.email.doctype.newsletter.newsletter.send_scheduled_email because it was found in queue for mysite.test
2025-02-05 18:06:00,757 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for mysite.test
2025-02-05 18:06:00,758 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for mysite.test
2025-02-05 18:06:00,760 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for mysite.test
2025-02-05 18:06:00,762 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for mysite.test
2025-02-05 18:06:00,766 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for mysite.test
2025-02-05 18:06:00,769 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for mysite.test
2025-02-05 18:06:00,771 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for mysite.test
2025-02-05 18:06:00,772 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for mysite.test
2025-02-05 18:06:00,774 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for mysite.test
2025-02-05 18:06:00,776 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for mysite.test
2025-02-05 18:06:00,780 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_calendar.google_calendar.sync because it was found in queue for mysite.test
2025-02-05 18:06:00,781 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for mysite.test
2025-02-05 18:06:00,785 ERROR scheduler Skipped queueing frappe.model.utils.link_count.update_link_count because it was found in queue for mysite.test
2025-02-05 18:06:00,792 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for money.test
2025-02-05 18:06:00,794 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for money.test
2025-02-05 18:06:00,796 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for money.test
2025-02-05 18:06:00,798 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for money.test
2025-02-05 18:06:00,801 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for money.test
2025-02-05 18:06:00,803 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for money.test
2025-02-05 18:06:00,804 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for money.test
2025-02-05 18:06:00,805 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for money.test
2025-02-05 18:06:00,807 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for money.test
2025-02-05 18:06:00,812 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for money.test
2025-02-05 18:06:00,816 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for money.test
2025-02-05 18:06:00,817 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for money.test
2025-02-05 18:06:00,821 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_calendar.google_calendar.sync because it was found in queue for money.test
2025-02-05 18:06:00,823 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for money.test
2025-02-05 18:06:00,825 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for money.test
2025-02-05 18:06:00,829 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for money.test
2025-02-05 18:22:00,138 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for mysite.test
2025-02-05 18:22:00,179 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for money.test
2025-02-05 18:22:00,186 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for money.test
2025-02-05 18:26:00,205 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for money.test
2025-02-05 18:26:00,218 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for money.test
2025-02-05 18:26:00,224 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for money.test
2025-02-05 18:26:00,231 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for money.test
2025-02-05 18:26:00,241 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for money.test
2025-02-05 18:26:00,243 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for money.test
2025-02-05 18:26:00,247 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for money.test
2025-02-05 18:26:00,252 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for money.test
2025-02-05 18:26:00,261 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for money.test
2025-02-05 18:26:00,290 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for mysite.test
2025-02-05 18:26:00,302 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for mysite.test
2025-02-05 18:30:00,372 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for mysite.test
2025-02-05 18:30:00,383 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for mysite.test
2025-02-05 18:30:00,391 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for money.test
2025-02-05 18:30:00,401 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for money.test
2025-02-05 18:30:00,403 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for money.test
2025-02-05 18:30:00,409 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for money.test
2025-02-05 18:30:00,411 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for money.test
2025-02-05 18:30:00,412 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for money.test
2025-02-05 18:30:00,414 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for money.test
2025-02-05 18:30:00,416 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for money.test
2025-02-05 18:30:00,418 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for money.test
2025-02-05 18:30:00,423 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for money.test
2025-02-05 18:30:00,425 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for money.test
2025-02-05 18:34:00,449 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for money.test
2025-02-05 18:34:00,466 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for money.test
2025-02-05 18:34:00,474 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for money.test
2025-02-05 18:34:00,479 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for money.test
2025-02-05 18:34:00,483 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for money.test
2025-02-05 18:34:00,486 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for money.test
2025-02-05 18:34:00,490 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for money.test
2025-02-05 18:34:00,492 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for money.test
2025-02-05 18:34:00,501 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for money.test
2025-02-05 18:34:00,504 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for money.test
2025-02-05 18:34:00,511 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for mysite.test
2025-02-05 18:34:00,514 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for mysite.test
2025-02-05 18:34:00,520 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for mysite.test
2025-02-05 18:34:00,535 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for mysite.test
2025-02-05 18:34:00,539 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for mysite.test
2025-02-05 18:34:00,540 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for mysite.test
2025-02-05 18:34:00,543 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for mysite.test
2025-02-05 18:34:00,547 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for mysite.test
2025-02-05 18:34:00,555 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for mysite.test
2025-02-05 18:34:00,556 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for mysite.test
2025-02-05 18:34:00,561 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for mysite.test
2025-02-05 18:34:00,562 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for mysite.test
2025-02-07 10:34:00,560 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_calendar.google_calendar.sync because it was found in queue for money.test
2025-02-07 10:34:00,565 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for money.test
2025-02-07 10:34:00,567 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for money.test
2025-02-07 10:34:00,570 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for money.test
2025-02-07 10:34:00,572 ERROR scheduler Skipped queueing frappe.desk.notifications.clear_notifications because it was found in queue for money.test
2025-02-07 10:34:00,574 ERROR scheduler Skipped queueing frappe.automation.doctype.auto_repeat.auto_repeat.make_auto_repeat_entry because it was found in queue for money.test
2025-02-07 10:34:00,575 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for money.test
2025-02-07 10:34:00,577 ERROR scheduler Skipped queueing frappe.desk.doctype.event.event.send_event_digest because it was found in queue for money.test
2025-02-07 10:34:00,579 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_drive.google_drive.daily_backup because it was found in queue for money.test
2025-02-07 10:34:00,581 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_daily_alerts because it was found in queue for money.test
2025-02-07 10:34:00,583 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for money.test
2025-02-07 10:34:00,585 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for money.test
2025-02-07 10:34:00,591 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for money.test
2025-02-07 10:34:00,593 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_daily_updates because it was found in queue for money.test
2025-02-07 10:34:00,594 ERROR scheduler Skipped queueing frappe.social.doctype.energy_point_settings.energy_point_settings.allocate_review_points because it was found in queue for money.test
2025-02-07 10:34:00,598 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for money.test
2025-02-07 10:34:00,599 ERROR scheduler Skipped queueing frappe.automation.doctype.auto_repeat.auto_repeat.set_auto_repeat_as_completed because it was found in queue for money.test
2025-02-07 10:34:00,600 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.remove_unverified_record because it was found in queue for money.test
2025-02-07 10:34:00,602 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for money.test
2025-02-07 10:34:00,604 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for money.test
2025-02-07 10:34:00,606 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for money.test
2025-02-07 10:34:00,607 ERROR scheduler Skipped queueing frappe.email.doctype.newsletter.newsletter.send_scheduled_email because it was found in queue for money.test
2025-02-07 10:34:00,608 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for money.test
2025-02-07 10:34:00,609 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for money.test
2025-02-07 10:34:00,610 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for money.test
2025-02-07 10:34:00,611 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for money.test
2025-02-07 10:34:00,615 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for mysite.test
2025-02-07 10:34:00,616 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_contacts.google_contacts.sync because it was found in queue for mysite.test
2025-02-07 10:34:00,617 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for mysite.test
2025-02-07 10:34:00,617 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.remove_unverified_record because it was found in queue for mysite.test
2025-02-07 10:34:00,619 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for mysite.test
2025-02-07 10:34:00,620 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for mysite.test
2025-02-07 10:34:00,621 ERROR scheduler Skipped queueing frappe.automation.doctype.auto_repeat.auto_repeat.make_auto_repeat_entry because it was found in queue for mysite.test
2025-02-07 10:34:00,622 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for mysite.test
2025-02-07 10:34:00,623 ERROR scheduler Skipped queueing frappe.desk.notifications.clear_notifications because it was found in queue for mysite.test
2025-02-07 10:34:00,624 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for mysite.test
2025-02-07 10:34:00,625 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for mysite.test
2025-02-07 10:34:00,626 ERROR scheduler Skipped queueing frappe.sessions.clear_expired_sessions because it was found in queue for mysite.test
2025-02-07 10:34:00,629 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for mysite.test
2025-02-07 10:34:00,630 ERROR scheduler Skipped queueing frappe.core.doctype.log_settings.log_settings.run_log_clean_up because it was found in queue for mysite.test
2025-02-07 10:34:00,631 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for mysite.test
2025-02-07 10:34:00,632 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_daily_alerts because it was found in queue for mysite.test
2025-02-07 10:34:00,633 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for mysite.test
2025-02-07 10:34:00,633 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for mysite.test
2025-02-07 10:34:00,634 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for mysite.test
2025-02-07 10:34:00,635 ERROR scheduler Skipped queueing frappe.email.doctype.newsletter.newsletter.send_scheduled_email because it was found in queue for mysite.test
2025-02-07 10:34:00,636 ERROR scheduler Skipped queueing frappe.model.utils.link_count.update_link_count because it was found in queue for mysite.test
2025-02-07 10:34:00,637 ERROR scheduler Skipped queueing frappe.automation.doctype.auto_repeat.auto_repeat.set_auto_repeat_as_completed because it was found in queue for mysite.test
2025-02-07 10:34:00,638 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for mysite.test
2025-02-07 10:34:00,639 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_drive.google_drive.daily_backup because it was found in queue for mysite.test
2025-02-07 10:34:00,640 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for mysite.test
2025-02-07 10:34:00,641 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_calendar.google_calendar.sync because it was found in queue for mysite.test
2025-02-07 10:34:00,642 ERROR scheduler Skipped queueing frappe.desk.doctype.event.event.send_event_digest because it was found in queue for mysite.test
2025-02-07 10:34:00,643 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for mysite.test
2025-02-07 10:34:00,644 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for mysite.test
2025-02-07 10:34:00,645 ERROR scheduler Skipped queueing frappe.social.doctype.energy_point_settings.energy_point_settings.allocate_review_points because it was found in queue for mysite.test
2025-02-07 10:34:00,646 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for mysite.test
2025-02-07 10:34:00,647 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for mysite.test
2025-02-07 10:34:00,648 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_daily_updates because it was found in queue for mysite.test
2025-02-07 10:34:00,648 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for mysite.test
2025-02-07 10:38:00,477 ERROR scheduler Skipped queueing frappe.desk.notifications.clear_notifications because it was found in queue for money.test
2025-02-07 10:42:00,538 ERROR scheduler Skipped queueing frappe.desk.notifications.clear_notifications because it was found in queue for money.test
2025-02-07 10:46:00,652 ERROR scheduler Skipped queueing frappe.desk.notifications.clear_notifications because it was found in queue for money.test
2025-02-07 12:30:00,511 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for mysite.test
2025-02-07 14:26:01,056 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 570, in can_read
    return self._parser.can_read(timeout)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/_parsers/hiredis.py", line 79, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/_parsers/hiredis.py", line 88, in read_from_socket
    bufflen = self._sock.recv_into(self._buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 1428, in get_connection
    if connection.can_read() and self.cache is None:
       ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 573, in can_read
    raise ConnectionError(f"Error while reading from {host_error}: {e.args}")
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:11000: (54, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect(error)
    )
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 108, in enqueue_events_for_site
    enqueue_events()
    ~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 128, in enqueue_events
    if job_type.enqueue():
       ~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 618, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 623, in get_job_status
    if job := get_job(job_id):
              ~~~~~~~^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 629, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
    ~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/rq/job.py", line 991, in refresh
    data = self.connection.hgetall(self.key)
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 1432, in get_connection
    connection.connect()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:11000. Connection refused.
2025-02-07 14:26:01,146 ERROR scheduler Exception in Enqueue Events for Site mysite.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect(error)
    )
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 108, in enqueue_events_for_site
    enqueue_events()
    ~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 128, in enqueue_events
    if job_type.enqueue():
       ~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 618, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 623, in get_job_status
    if job := get_job(job_id):
              ~~~~~~~^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 629, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
    ~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/rq/job.py", line 991, in refresh
    data = self.connection.hgetall(self.key)
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:11000. Connection refused.
2025-02-07 15:18:00,119 ERROR scheduler Exception in Enqueue Events for Site manikanta.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_cac0ab9f6a005367'@'localhost' (using password: YES)")
2025-02-08 10:06:00,565 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 10:10:00,623 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 10:14:00,634 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 10:18:00,771 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 10:22:00,784 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 10:26:00,892 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 10:30:00,926 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 10:34:01,006 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 10:46:01,194 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 10:50:00,281 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 10:54:00,291 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 10:58:00,426 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 11:02:00,502 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
2025-02-08 11:06:00,599 ERROR scheduler Exception in Enqueue Events for Site money.test
Traceback (most recent call last):
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events_for_site
    if is_scheduler_inactive():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 149, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 162, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 869, in get_single_value
    ).run()
      ~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 215, in sql
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/database.py", line 120, in connect
    self._conn: MariadbConnection | PostgresConnection = self.get_connection()
                                                         ~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/saimanikanta/Desktop/ezapp/ez/frappe-bench/env/lib/python3.13/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1044, "Access denied for user '_7c5f4f77b0d74777'@'localhost' to database 'f77b0d74777_7c5f4'")
